# Generated by Django 5.2.8 on 2025-11-23 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0003_remove_post_image_alter_post_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="posts/"),
        ),
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.CharField(max_length=280),
        ),
    ]
