# Generated by Django 5.2.8 on 2025-11-23 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0004_post_image_alter_post_content"),
    ]

    operations = []
